export const Types = {

  ORDER_REPOSITORY: Symbol.for("ORDER_REPOSITORY"),
  ORDER_CONTROLLER: Symbol.for("ORDER_CONTROLLER"),
  ORDER_DOMAIN_SERVICE: Symbol.for("ORDER_DOMAIN_SERVICE"),
  ORDER_APPLICATION_SERVICE: Symbol.for("ORDER_APPLICATION_SERVICE"),

  PRODUCT_REPOSITORY: Symbol.for("PRODUCT_REPOSITORY"),
  PRODUCT_CONTROLLER: Symbol.for("PRODUCT_CONTROLLER"),
  PRODUCT_APPLICATION_SERVICE: Symbol.for("PRODUCT_APPLICATION_SERVICE"),

  ORDER_DETAIL_REPOSITORY: Symbol.for("ORDER_DETAIL_REPOSITORY"),

  CUSTOMER_REPOSITORY: Symbol.for("CUSTOMER_REPOSITORY"),
  CUSTOMER_CONTROLLER: Symbol.for("CUSTOMER_CONTROLLER"),
  CUSTOMER_DOMAIN_SERVICE: Symbol.for("CUSTOMER_DOMAIN_SERVICE"),
  CUSTOMER_APPLICATION_SERVICE: Symbol.for("CUSTOMER_APPLICATION_SERVICE"),
};
